# All the properties related to spring-boot application/default overrides are kept here - eg. overriding the default
# server port from 8080 to 9090
server.port=9090
server.servlet.context-path=/spring-boot-app
# Banner properties
spring.main.banner-mode=off
# Spring Cache Location
spring.cache.ehcache.config=classpath:springboot/template/cache/ehcache.xml