# Root logger option
log4j.rootLogger=INFO, stdout
# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
# Common logging(s)
log4j.logger.org.apache.commons=WARN
log4j.logger.org.springframework=ERROR
log4j.logger.org.springframework.plugin=ERROR
log4j.logger.com.mybatis=WARN
log4j.logger.java.sql=WARN
log4j.logger.org.apache=WARN
log4j.logger.net=WARN
log4j.logger.org.springframework.boot=WARN
log4j.logger.org.hibernate.validator=ERROR
log4j.logger.io.springfox=ERROR
log4j.logger.io.swagger=ERROR
log4j.logger.com.zaxxer=WARN